#!/bin/bash
#This Script Was Made By @shadow
#Colors
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
Purple="\033[0;35m"
Cyan="\033[0;36m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
blue="\033[1;34m"
clear

banner()
{
echo -e "$red" "$@"
  echo "+------------------------------------------+"
}

banner "
╔═══╦╗──────╔╗
║╔═╗║║──────║║
║╚══╣╚═╦══╦═╝╠══╦╗╔╗╔╗
╚══╗║╔╗║╔╗║╔╗║╔╗║╚╝╚╝║
║╚═╝║║║║╔╗║╚╝║╚╝╠╗╔╗╔╝
╚═══╩╝╚╩╝╚╩══╩══╝╚╝╚╝"nc 

echo -e "$red"
   
    echo "
    __________________________________________________________________________________________
      |                                                                                         |
      |  {@} Coded By shadow                                    |
      |_________________________________________________________________________________________|"

 echo -e "$red"                       ">>>>>>>>>>>>>>>>   MENU   <<<<<<<<<<<<<<<<<<

{1} My Ip
{2} Track Ip
{3} Find MAC Address Vendors
{4} Exit)
┌─[ Enter the your choice ]─[~]
└──╼ #  "

myip="1"
trackip="2"
mal="3"
ex="4"

read a
if [ "$a" == "$myip" ]
then
clear

banner()
{
echo -e "$red" "$@"
  echo "+------------------------------------------+"
}

banner "
╔═══╦╗──────╔╗
║╔═╗║║──────║║
║╚══╣╚═╦══╦═╝╠══╦╗╔╗╔╗
╚══╗║╔╗║╔╗║╔╗║╔╗║╚╝╚╝║
║╚═╝║║║║╔╗║╚╝║╚╝╠╗╔╗╔╝
╚═══╩╝╚╩╝╚╩══╩══╝╚╝╚╝"nc                   
echo "Coded By shadow"

printf '      Ip             :       '
      curl -s https://ipinfo.io/json | jq -r '.ip'
printf '      Country        :       '
      curl -s https://ipapi.co//json | jq -r  '.country_name'
printf '      Region         :       '
      curl -s https://ipapi.co//json | jq -r  '.region'
printf '      City           :       '
      curl -s https://ipapi.co//json | jq -r '.city'
printf '      Postal Code    :       '
      curl -s https://ipapi.co//json | jq -r  '.postal'
echo

printf '      Latitude       :       '
      curl -s https://ipapi.co//json | jq -r  '.latitude'
printf '      Longitude      :       '
      curl -s https://ipapi.co//json | jq -r  '.longitude'

echo
printf '      Isp            :       '
     curl -s https://ipinfo.io/ | jq -r  '.org'

echo

printf '      Timezone       :       '
     curl -s https://ipinfo.io/json | jq -r '.timezone'
printf '      Currency       :       '
     curl -s https://ipapi.co//json | jq -r  '.currency'
printf '      Calling code   :       '
     curl -s https://ipapi.co//json | jq -r  '.country_calling_code'

echo

echo -e -n "\e[0;31mReturn To  Menu (Press Enter)\e[0m  "
read yes


read a
  elif [ "$a" == "$trackip" ]
then
clear

echobanner()
{
echo -e "$red" "$@"
  echo "+------------------------------------------+"
}

banner "
╔═══╦╗──────╔╗
║╔═╗║║──────║║
║╚══╣╚═╦══╦═╝╠══╦╗╔╗╔╗
╚══╗║╔╗║╔╗║╔╗║╔╗║╚╝╚╝║
║╚═╝║║║║╔╗║╚╝║╚╝╠╗╔╗╔╝
╚═══╩╝╚╩╝╚╩══╩══╝╚╝╚╝"n
echo "                                                      Coded By CyberGhost"                                                                                                                    
echo -e -n "Enter ip address : "
read ip

echo

printf '      Ip             :       '
      curl -s https://ipinfo.io/$ip/json | jq -r '.ip'
printf '      Country        :       '
      curl -s https://ipapi.co/$ip//json | jq -r  '.country_name'
printf '      Region         :       '
      curl -s https://ipapi.co/$ip//json | jq -r  '.region'
printf '      City           :       '
      curl -s https://ipapi.co/$ip//json | jq -r '.city'
printf '      Postal Code    :       '
      curl -s https://ipapi.co/$ip//json | jq -r  '.postal'
echo

printf '      Location       :       '
      curl -s https://ipinfo.io/$ip/json | jq -r  '.loc'


echo
printf '      Isp            :       '
     curl -s https://ipinfo.io/$ip/json | jq -r  '.org'

echo

printf '      Timezone       :       '
     curl -s https://ipinfo.io/$ip/json | jq -r '.timezone'
printf '      Currency       :       '
     curl -s https://ipapi.co/$ip//json | jq -r  '.currency'
printf '      Calling code   :       '
     curl -s https://ipapi.co/$ip//json | jq -r  '.country_calling_code'

echo

echo -e -n "\e[0;31mReturn To  Menu (Press Enter)\e[0m  "
read yes

./infofinder


read a
  elif [ "$a" == "$mal" ]
then
clear

banner()
{
echo -e "$red" "$@"
  echo "+------------------------------------------+"
}

banner "
╔═══╦╗──────╔╗
║╔═╗║║──────║║
║╚══╣╚═╦══╦═╝╠══╦╗╔╗╔╗
╚══╗║╔╗║╔╗║╔╗║╔╗║╚╝╚╝║
║╚═╝║║║║╔╗║╚╝║╚╝╠╗╔╗╔╝
╚═══╩╝╚╩╝╚╩══╩══╝╚╝╚╝"nc 
echo "
                                                        Coded By CyberGhost"


echo -e -n "Enter MAC address : "
read MAC

echo

printf '      Vendor / Company             :       '

curl -s http://api.macvendors.com/$MAC

echo
echo

echo -e -n "\e[0;31mReturn To  Menu (Press Enter)\e[0m  "
read yes

./infofinder


read a
elif [ "$a" == "$luwi" ]
then

clear

banner()
{
echo -e "$red" "$@"
  echo "+------------------------------------------+"
}

banner "
╔═══╦╗──────╔╗
║╔═╗║║──────║║
║╚══╣╚═╦══╦═╝╠══╦╗╔╗╔╗
╚══╗║╔╗║╔╗║╔╗║╔╗║╚╝╚╝║
║╚═╝║║║║╔╗║╚╝║╚╝╠╗╔╗╔╝
╚═══╩╝╚╩╝╚╩══╩══╝╚╝╚╝"nc 
echo "
                                                        Coded By shadow"

echo -e -n "Enter domain name  : "
read domain

whois $domain

echo

echo -e -n "\e[0;31mReturn To  Menu (Press Enter)\e[0m  "
read yes

./infofinder


read a
elif [ "$a" == "$ex" ]
then


exit










fi
